name: Deploy Google Apps Scripts

on:
  push:
    branches: [master]
    paths:
      - 'apps_script/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - run: npm install -g @google/clasp
    
    - name: Create clasprc.json file
      run: |
        echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

    # Deploy ProcessVideos.js
    - name: Create .clasp.json for ProcessVideos
      run: |
        echo '${{ secrets.CLASP_JSON_PROCESS_VIDEOS }}' > .clasp.json
    - name: Deploy ProcessVideos with clasp
      run: clasp push -f ProcessVideos.js

    # Deploy Code_v2.js
    - name: Create .clasp.json for Code_v2
      run: |
        echo '${{ secrets.CLASP_JSON }}' > .clasp.json
    - name: Deploy Code_v2 with clasp
      run: clasp push -f Code.js
