name: Deploy Google Apps Scripts

on:
  push:
    branches: [master]
    paths:
      - 'apps_script/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - run: npm install -g @google/clasp
    
    - name: Create clasprc.json file
      run: |
        echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

    - name: Create .clasp.json 
      working-directory: apps_script
      run: |
        echo '${{ secrets.CLASP_JSON }}' > .clasp.json
        
    - name: Deploy scripts
      working-directory: apps_script
      run: clasp push --force